yes |pkg install glu
yes |pkg install mesa
yes |pkg install mesa-demos
yes |pkg install mesa-dev
yes |pkg install mesa-vulkan-icd-freedreno
yes |pkg install mesa-vulkan-icd-freedreno-dri3
yes |pkg install mesa-vulkan-icd-swrast
yes |pkg install osmesa
yes |pkg install osmesa-demos
