/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_swing_JTextArea_AccessibleJTextArea */

#ifndef _Included_javax_swing_JTextArea_AccessibleJTextArea
#define _Included_javax_swing_JTextArea_AccessibleJTextArea
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_swing_JTextArea_AccessibleJTextArea_serialVersionUID
#define javax_swing_JTextArea_AccessibleJTextArea_serialVersionUID 642321655757800191i64
#undef javax_swing_JTextArea_AccessibleJTextArea_serialVersionUID
#define javax_swing_JTextArea_AccessibleJTextArea_serialVersionUID 5081320404842566097i64
#ifdef __cplusplus
}
#endif
#endif
