/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_swing_JTextField_NotifyAction */

#ifndef _Included_javax_swing_JTextField_NotifyAction
#define _Included_javax_swing_JTextField_NotifyAction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
