/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_awt_Frame_AccessibleAWTFrame */

#ifndef _Included_java_awt_Frame_AccessibleAWTFrame
#define _Included_java_awt_Frame_AccessibleAWTFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_Frame_AccessibleAWTFrame_serialVersionUID
#define java_awt_Frame_AccessibleAWTFrame_serialVersionUID 642321655757800191i64
#undef java_awt_Frame_AccessibleAWTFrame_serialVersionUID
#define java_awt_Frame_AccessibleAWTFrame_serialVersionUID 5081320404842566097i64
#undef java_awt_Frame_AccessibleAWTFrame_serialVersionUID
#define java_awt_Frame_AccessibleAWTFrame_serialVersionUID 4215068635060671780i64
#undef java_awt_Frame_AccessibleAWTFrame_serialVersionUID
#define java_awt_Frame_AccessibleAWTFrame_serialVersionUID -6172960752956030250i64
#ifdef __cplusplus
}
#endif
#endif
