/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_swing_JTextField_AccessibleJTextField */

#ifndef _Included_javax_swing_JTextField_AccessibleJTextField
#define _Included_javax_swing_JTextField_AccessibleJTextField
#ifdef __cplusplus
extern "C" {
#endif
#undef javax_swing_JTextField_AccessibleJTextField_serialVersionUID
#define javax_swing_JTextField_AccessibleJTextField_serialVersionUID 642321655757800191i64
#undef javax_swing_JTextField_AccessibleJTextField_serialVersionUID
#define javax_swing_JTextField_AccessibleJTextField_serialVersionUID 5081320404842566097i64
#ifdef __cplusplus
}
#endif
#endif
